include:
  remote: https://git.studer-raimann.ch/gitlab-ci/templates/review_apps.yml

variables:
  REVIEW_APP_IMAGE: sturai/ilias-dev:latest
  REVIEW_APP_DEST: /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P

#test:
#  stage: test
#  tags:
#    - php7
#  before_script:
#    # TODO: Install phpunit, etc.
#    - php --version
#  script:
#    # TODO: Run unit tests, etc.
#    - echo "Running unit tests..."

review:
  extends: .review_deployment
  environment:
    on_stop: stop_review
  script:
    - srag-review deploy

stop_review:
  extends: .review_deployment
  environment:
    action: stop
  script:
    - srag-review stop
